replicaCount: 3

image:
  repository: container/app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

containerPort: 8080

environment:
log_level:
google_firestore_project:
service_account_name:
