name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform.yaml'
      - 'deploy/terraform/**'

jobs:
  terraform:
    name: Terraform - Prod
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: deploy/terraform
    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_environment: "prod"
      TF_VAR_workload_identity_namespace: ${{ vars.WORKLOAD_IDENTITY_NAMESPACE }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Init
        run: terraform init

      - name: fmt
        run: terraform fmt -check

      - name: validate
        run: terraform validate

      - name: Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Show
        run: terraform show tfplan

      - name: Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
